"""Plot the synthetic glucose trace generated by ``make_fake_single_meal_trace.py``.

Loads ``example/data_single_meal.parquet`` and renders the simulated CGM
trace (with the 70-180 mg/dL target band and meal markers) over a second panel
showing the CHO and bolus inputs. Saves the figure to
``example/data_single_meal.png``.

Run with::

    PYTHONPATH=. uv run python example/plot_fake_single_meal_trace.py
"""

import os

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Per-label marker colours (single-meal model ignores meal type; labels are cosmetic).
LABEL_COLORS = {"M": "#8c564b"}


def main():
    here = os.path.abspath(os.path.dirname(__file__))
    df = pd.read_parquet(os.path.join(here, "data_single_meal.parquet"))
    df["t"] = pd.to_datetime(df["t"])

    fig, (ax, ax2) = plt.subplots(
        2, 1, figsize=(14, 7), sharex=True,
        gridspec_kw={"height_ratios": [3, 1]},
    )

    # --- Glucose trace ---
    ax.plot(df["t"], df["glucose"], color="#1f77b4", lw=1.6,
            label="Simulated CGM (IG)")
    ax.axhspan(70, 180, color="#2ca02c", alpha=0.08, label="Target 70-180")
    ax.axhline(70, color="#d62728", ls="--", lw=0.9, alpha=0.7)
    ax.axhline(180, color="#ff7f0e", ls="--", lw=0.9, alpha=0.7)

    for _, r in df[df["cho"] > 0].iterrows():
        lab = r["cho_label"]
        col = LABEL_COLORS.get(lab, "k")
        ax.plot(r["t"], r["glucose"], "v", color=col, ms=8)
        ax.annotate(f"{lab}\n{r['cho']:.0f} g/min", (r["t"], r["glucose"]),
                    textcoords="offset points", xytext=(0, 14), ha="center",
                    fontsize=8, color=col, fontweight="bold")

    ax.set_ylabel("Glucose (mg/dL)")
    ax.set_title("Fake trace - data_single_meal.parquet "
                 "(single-meal, default params)")
    ax.legend(loc="upper right", fontsize=9)
    ax.grid(alpha=0.25)

    # --- Inputs: carbs and boluses ---
    m = df[df["cho"] > 0]
    ax2.stem(m["t"], m["cho"], linefmt="#8c564b", markerfmt="o", basefmt=" ",
             label="CHO (g/min)")
    b = df[df["bolus"] > 0]
    ax2.stem(b["t"], b["bolus"], linefmt="#1f77b4", markerfmt="s", basefmt=" ",
             label="Bolus (U)")
    ax2.set_ylabel("CHO / Bolus")
    ax2.set_xlabel("Time")
    ax2.legend(loc="upper right", fontsize=9)
    ax2.grid(alpha=0.25)
    ax2.xaxis.set_major_locator(mdates.HourLocator(interval=3))
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%d-%b\n%H:%M"))

    fig.tight_layout()
    out = os.path.join(here, "data_single_meal.png")
    fig.savefig(out, dpi=110, bbox_inches="tight")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
